- :file: 1.html
  :desc: Seasonal product
  :uri: http://lcbo.com/lcbo-ear/lcbo/product/details.do?language=EN&itemNumber=234880
  :method: :get
  :query_params:
    :id: 234880
  :expectation:
    :id: 234880
    :name: Muskoka Lakes Georgian Bay Rose Qc
    :tags:
    - muskoka
    - lakes
    - georgian
    - bay
    - rose
    - qc
    - wine
    - specialty
    - winesother
    - ontario
    - canada
    - winery
    - bottle
    :price_in_cents: 1695
    :regular_price_in_cents: 1695
    :clearance_sale_savings_in_cents: 0
    :limited_time_offer_savings_in_cents: 0
    :limited_time_offer_ends_on:
    :bonus_reward_miles: 0
    :bonus_reward_miles_ends_on:
    :stock_type: LCBO
    :primary_category: Wine
    :secondary_category: Specialty Wines/Other
    :tertiary_category: Fruit Wine
    :origin: Ontario, Canada
    :package: 750 mL bottle
    :package_unit_type: bottle
    :package_unit_volume_in_milliliters: 750
    :total_package_units: 1
    :total_package_volume_in_milliliters: 750
    :volume_in_milliliters: 750
    :alcohol_content: 1250
    :price_per_liter_of_alcohol_in_cents: 1808
    :price_per_liter_in_cents: 2260
    :style:
    :sugar_content:
    :sugar_in_grams_per_liter: 33
    :producer_name: Muskoka Lakes Winery
    :varietal: Rose Wines
    :released_on:
    :is_discontinued: false
    :has_limited_time_offer: false
    :has_clearance_sale: false
    :has_bonus_reward_miles: false
    :has_value_added_promotion: false
    :is_seasonal: true
    :is_vqa: false
    :is_kosher: false
    :description:
    :serving_suggestion:
    :tasting_note: The granite shores of Georgian Bay yield crisp, sweet apples, and tart,
      mouth-watering cranberries. Together, they make a crisp, dry, refreshing wine. The
      nose is tree fruit with a hint of peach and floral notes. On the palate, it is fruit
      forward, with good acidity and a dry, lingering finish. A perfect sipping wine,
      or pair with poached salmon or grilled chicken.
    :value_added_promotion_description:
    :image_thumb_url: http://lcbo.com/app/images/products/website/0234880.jpg
    :image_url: http://lcbo.com/app/images/products/0234880.jpg

- :file: 2.html
  :desc: Product with limited time offer
  :uri: http://lcbo.com/lcbo-ear/lcbo/product/details.do?language=EN&itemNumber=105742
  :method: :get
  :query_params:
    :id: 105742
  :expectation:
    :id: 105742
    :name: Appleton Estate Extra Rum
    :tags:
    - appleton
    - estate
    - extra
    - rum
    - spirits
    - jamaica
    - j
    - wray
    - nephew
    - limited
    - bottle
    :price_in_cents: 3495
    :regular_price_in_cents: 3895
    :clearance_sale_savings_in_cents: 0
    :limited_time_offer_savings_in_cents: 400
    :limited_time_offer_ends_on: 2012-12-02
    :bonus_reward_miles: 0
    :bonus_reward_miles_ends_on:
    :stock_type: LCBO
    :primary_category: Spirits
    :secondary_category: Rum
    :tertiary_category: Light/Amber
    :origin: Jamaica
    :package: 750 mL bottle
    :package_unit_type: bottle
    :package_unit_volume_in_milliliters: 750
    :total_package_units: 1
    :total_package_volume_in_milliliters: 750
    :volume_in_milliliters: 750
    :alcohol_content: 4300
    :price_per_liter_of_alcohol_in_cents: 1083
    :price_per_liter_in_cents: 4660
    :style:
    :sugar_content:
    :sugar_in_grams_per_liter:
    :producer_name: J. Wray & Nephew Limited
    :varietal:
    :released_on:
    :is_discontinued: false
    :has_limited_time_offer: true
    :has_clearance_sale: false
    :has_bonus_reward_miles: false
    :has_value_added_promotion: false
    :is_seasonal: false
    :is_vqa: false
    :is_kosher: false
    :description:
    :serving_suggestion: Serve neat; on the rocks; with cola; on in cooking recipes.
    :tasting_note: Deep golden/copper colour; vanilla bean, caramel/molasses, buchwheat
      honey and spicey cinamon/nutmeg aromas; quite elegant on palate with warm, mildly
      spicy, brown sugar flavours and a smooth, lingering finish.
    :value_added_promotion_description:
    :image_thumb_url: http://lcbo.com/app/images/products/website/0105742.jpg
    :image_url: http://lcbo.com/app/images/products/0105742.jpg

- :file: 3.html
  :desc: Product with bonus air miles
  :uri: http://lcbo.com/lcbo-ear/lcbo/product/details.do?language=EN&itemNumber=508614
  :method: :get
  :query_params:
    :id: 508614
  :expectation:
    :id: 508614
    :name: Veuve Clicquot Ponsardin Brut Champagne
    :tags:
    - veuve
    - clicquot
    - ponsardin
    - brut
    - champagne
    - wine
    - france
    - clicquot-ponsardin
    - clicquotponsardin
    - sa
    - bottle
    :price_in_cents: 9195
    :regular_price_in_cents: 9195
    :clearance_sale_savings_in_cents: 0
    :limited_time_offer_savings_in_cents: 0
    :limited_time_offer_ends_on:
    :bonus_reward_miles: 25
    :bonus_reward_miles_ends_on: 2012-12-01
    :stock_type: VINTAGES
    :primary_category: Wine
    :secondary_category: Champagne
    :tertiary_category:
    :origin: Champagne, France
    :package: 750 mL bottle
    :package_unit_type: bottle
    :package_unit_volume_in_milliliters: 750
    :total_package_units: 1
    :total_package_volume_in_milliliters: 750
    :volume_in_milliliters: 750
    :alcohol_content: 1200
    :price_per_liter_of_alcohol_in_cents: 10216
    :price_per_liter_in_cents: 12260
    :style: Rich & Complex
    :sugar_content: XD - Extra Dry
    :sugar_in_grams_per_liter: 8
    :producer_name: Veuve Clicquot-Ponsardin S.A.
    :varietal: Sparkling (Champagne)
    :released_on: 2012-04-18
    :is_discontinued: false
    :has_limited_time_offer: false
    :has_clearance_sale: false
    :has_bonus_reward_miles: true
    :has_value_added_promotion: false
    :is_seasonal: false
    :is_vqa: false
    :is_kosher: false
    :description: An iconoclast like Veuve Cliquot herself (who took over her husband's
      domaine after his passing in 1805), this rich and racy bubbly has notes of date,
      apple, black raspberry and bread dough. Deserving of a fine meal like king crab
      legs or lobster-stuffed ravioli.
    :serving_suggestion:
    :tasting_note:
    :value_added_promotion_description:
    :image_thumb_url: http://lcbo.com/app/images/products/website/0508614.jpg
    :image_url: http://lcbo.com/app/images/products/0508614.jpg

- :file: 4.html
  :desc: Discontinued product
  :uri: http://lcbo.com/lcbo-ear/lcbo/product/details.do?language=EN&itemNumber=586214
  :method: :get
  :query_params:
    :id: 586214
  :expectation:
    :id: 586214
    :name: Woody's Ice Blueberry 330 Ml-B
    :tags:
    - woody's
    - woodys
    - ice
    - blueberry
    - '330'
    - ml
    - b
    - ml-b
    - mlb
    - ready
    - to
    - drinkcoolers
    - ready-to-drinkcoolers
    - readytodrinkcoolers
    - spirit
    - coolers
    - england
    - united
    - kingdom
    - beverage
    - brands
    - ltd
    - bottle
    :price_in_cents: 225
    :regular_price_in_cents: 225
    :clearance_sale_savings_in_cents: 0
    :limited_time_offer_savings_in_cents: 0
    :limited_time_offer_ends_on:
    :bonus_reward_miles: 0
    :bonus_reward_miles_ends_on:
    :stock_type: LCBO
    :primary_category: Ready-to-Drink/Coolers
    :secondary_category: Spirit Coolers
    :tertiary_category:
    :origin: England, United Kingdom
    :package: 330 mL bottle
    :package_unit_type: bottle
    :package_unit_volume_in_milliliters: 330
    :total_package_units: 1
    :total_package_volume_in_milliliters: 330
    :volume_in_milliliters: 330
    :alcohol_content: 550
    :price_per_liter_of_alcohol_in_cents: 1239
    :price_per_liter_in_cents: 681
    :style:
    :sugar_content:
    :sugar_in_grams_per_liter:
    :producer_name: Beverage Brands Ltd.
    :varietal:
    :released_on:
    :is_discontinued: true
    :has_limited_time_offer: false
    :has_clearance_sale: false
    :has_bonus_reward_miles: false
    :has_value_added_promotion: false
    :is_seasonal: false
    :is_vqa: false
    :is_kosher: false
    :description:
    :serving_suggestion:
    :tasting_note:
    :value_added_promotion_description:
    :image_thumb_url:
    :image_url:

- :file: 5.html
  :desc: Standard product
  :uri: http://lcbo.com/lcbo-ear/lcbo/product/details.do?language=EN&itemNumber=582973
  :method: :get
  :query_params:
    :id: 582973
  :expectation:
    :id: 582973
    :name: Bombay Sapphire London Dry Gin
    :tags:
    - bombay
    - sapphire
    - london
    - dry
    - gin
    - spirits
    - england
    - united
    - kingdom
    - company
    - ltd
    - bottle
    :price_in_cents: 5595
    :regular_price_in_cents: 5595
    :clearance_sale_savings_in_cents: 0
    :limited_time_offer_savings_in_cents: 0
    :limited_time_offer_ends_on:
    :bonus_reward_miles: 0
    :bonus_reward_miles_ends_on:
    :stock_type: LCBO
    :primary_category: Spirits
    :secondary_category: Gin
    :tertiary_category:
    :origin: England, United Kingdom
    :package: 1750 mL bottle
    :package_unit_type: bottle
    :package_unit_volume_in_milliliters: 1750
    :total_package_units: 1
    :total_package_volume_in_milliliters: 1750
    :volume_in_milliliters: 1750
    :alcohol_content: 4000
    :price_per_liter_of_alcohol_in_cents: 799
    :price_per_liter_in_cents: 3197
    :style:
    :sugar_content:
    :sugar_in_grams_per_liter:
    :producer_name: Bombay Spirits Company Ltd.
    :varietal:
    :released_on:
    :is_discontinued: false
    :has_limited_time_offer: false
    :has_clearance_sale: false
    :has_bonus_reward_miles: false
    :has_value_added_promotion: false
    :is_seasonal: false
    :is_vqa: false
    :is_kosher: false
    :description:
    :serving_suggestion: Serve with grilled shrimp, or use in classic gin & tonic or martini
    :tasting_note: Clear water white; complex mix of herbs and juniper on the nose with
      crisp lemon peel and citrus flavours; smooth and refreshing
    :value_added_promotion_description:
    :image_thumb_url:
    :image_url:

- :file: 6.html
  :desc: VQA product
  :uri: http://lcbo.com/lcbo-ear/lcbo/product/details.do?language=EN&itemNumber=125310
  :method: :get
  :query_params:
    :id: 125310
  :expectation:
    :id: 125310
    :name: Norman Hardie County Unfiltered Pinot Noir 2010
    :tags:
    - norman
    - hardie
    - county
    - unfiltered
    - pinot
    - noir
    - '2010'
    - wine
    - red
    - ontario
    - canada
    - wines
    - bottle
    :price_in_cents: 3500
    :regular_price_in_cents: 3500
    :clearance_sale_savings_in_cents: 0
    :limited_time_offer_savings_in_cents: 0
    :limited_time_offer_ends_on:
    :bonus_reward_miles: 0
    :bonus_reward_miles_ends_on:
    :stock_type: VINTAGES
    :primary_category: Wine
    :secondary_category: Red Wine
    :tertiary_category:
    :origin: Ontario, Canada
    :package: 750 mL bottle
    :package_unit_type: bottle
    :package_unit_volume_in_milliliters: 750
    :total_package_units: 1
    :total_package_volume_in_milliliters: 750
    :volume_in_milliliters: 750
    :alcohol_content: 1150
    :price_per_liter_of_alcohol_in_cents: 4057
    :price_per_liter_in_cents: 4666
    :style:
    :sugar_content:
    :sugar_in_grams_per_liter: 3
    :producer_name: Hardie Wines
    :varietal: Pinot Noir
    :released_on:
    :is_discontinued: false
    :has_limited_time_offer: false
    :has_clearance_sale: false
    :has_bonus_reward_miles: false
    :has_value_added_promotion: false
    :is_seasonal: false
    :is_vqa: true
    :is_kosher: false
    :description:
    :serving_suggestion:
    :tasting_note:
    :value_added_promotion_description:
    :image_thumb_url: http://lcbo.com/app/images/products/website/0125310.jpg
    :image_url: http://lcbo.com/app/images/products/0125310.jpg

- :file: 7.html
  :desc: Kosher Product
  :uri: http://lcbo.com/lcbo-ear/lcbo/product/details.do?language=EN&itemNumber=256453
  :method: :get
  :query_params:
    :id: 256453
  :expectation:
    :id: 256453
    :name: Coco de Java Liqueur K
    :tags:
    - coco
    - de
    - java
    - liqueur
    - k
    - spirits
    - liqueurliquor
    - usa
    - castle
    - bottle
    :price_in_cents: 2790
    :regular_price_in_cents: 3495
    :clearance_sale_savings_in_cents: 705
    :limited_time_offer_savings_in_cents: 0
    :limited_time_offer_ends_on:
    :bonus_reward_miles: 0
    :bonus_reward_miles_ends_on:
    :stock_type: VINTAGES
    :primary_category: Spirits
    :secondary_category: Liqueur/Liquor
    :tertiary_category: Coffee
    :origin: USA
    :package: 750 mL bottle
    :package_unit_type: bottle
    :package_unit_volume_in_milliliters: 750
    :total_package_units: 1
    :total_package_volume_in_milliliters: 750
    :volume_in_milliliters: 750
    :alcohol_content: 2400
    :price_per_liter_of_alcohol_in_cents: 1550
    :price_per_liter_in_cents: 3720
    :style:
    :sugar_content:
    :sugar_in_grams_per_liter:
    :producer_name: Castle Spirits
    :varietal:
    :released_on:
    :is_discontinued: false
    :has_limited_time_offer: false
    :has_clearance_sale: true
    :has_bonus_reward_miles: false
    :has_value_added_promotion: false
    :is_seasonal: false
    :is_vqa: false
    :is_kosher: true
    :description:
    :serving_suggestion:
    :tasting_note:
    :value_added_promotion_description:
    :image_thumb_url:
    :image_url:

- :file: 8.html
  :desc: Product with Value Added Promotion
  :uri: http://lcbo.com/lcbo-ear/lcbo/product/details.do?language=EN&itemNumber=42
  :method: :get
  :query_params:
    :id: 42
  :expectation:
    :id: 42
    :name: Canadian Club Whisky
    :tags:
    - canadian
    - club
    - whisky
    - spirits
    - whiskywhiskey
    - canada
    - company
    - bottle
    :price_in_cents: 2495
    :regular_price_in_cents: 2495
    :clearance_sale_savings_in_cents: 0
    :limited_time_offer_savings_in_cents: 0
    :limited_time_offer_ends_on:
    :bonus_reward_miles: 0
    :bonus_reward_miles_ends_on:
    :stock_type: LCBO
    :primary_category: Spirits
    :secondary_category: Whisky/Whiskey
    :tertiary_category: Canadian
    :origin: Canada
    :package: 750 mL bottle
    :package_unit_type: bottle
    :package_unit_volume_in_milliliters: 750
    :total_package_units: 1
    :total_package_volume_in_milliliters: 750
    :volume_in_milliliters: 750
    :alcohol_content: 4000
    :price_per_liter_of_alcohol_in_cents: 831
    :price_per_liter_in_cents: 3326
    :style:
    :sugar_content:
    :sugar_in_grams_per_liter:
    :producer_name: Canadian Club Whisky Company
    :varietal:
    :released_on:
    :is_discontinued: false
    :has_limited_time_offer: false
    :has_clearance_sale: false
    :has_bonus_reward_miles: false
    :has_value_added_promotion: true
    :is_seasonal: false
    :is_vqa: false
    :is_kosher: false
    :description:
    :serving_suggestion: On the rocks or in a cocktail
    :tasting_note: Golden amber colour; corn mash nose with peach & vanilla notes; matching
      smooth flavour
    :value_added_promotion_description: 750 mL bottle comes with FREE Devil's Cut 50ml
      until Dec 1, 2012 or while supplies last!
    :image_thumb_url: http://lcbo.com/app/images/products/website/0000042.jpg
    :image_url: http://lcbo.com/app/images/products/0000042.jpg

- :file: 9.html
  :desc: Vintages product with no image
  :uri: http://lcbo.com/lcbo-ear/lcbo/product/details.do?language=EN&itemNumber=965293
  :method: :get
  :query_params:
    :id: 965293
  :expectation:
    :id: 965293
    :name: ! '''Luce'' Grappa'
    :tags:
    - ! '''luce'''
    - luce
    - grappa
    - spirits
    - eau
    - de
    - vie
    - eau-de-vie
    - eaudevie
    - italy
    - bottle
    :price_in_cents: 6995
    :regular_price_in_cents: 6995
    :clearance_sale_savings_in_cents: 0
    :limited_time_offer_savings_in_cents: 0
    :limited_time_offer_ends_on:
    :bonus_reward_miles: 0
    :bonus_reward_miles_ends_on:
    :stock_type: VINTAGES
    :primary_category: Spirits
    :secondary_category: Eau-de-Vie
    :tertiary_category: Grappa
    :origin: Italy
    :package: 500 mL bottle
    :package_unit_type: bottle
    :package_unit_volume_in_milliliters: 500
    :total_package_units: 1
    :total_package_volume_in_milliliters: 500
    :volume_in_milliliters: 500
    :alcohol_content: 4000
    :price_per_liter_of_alcohol_in_cents: 3497
    :price_per_liter_in_cents: 13990
    :style:
    :sugar_content:
    :sugar_in_grams_per_liter:
    :producer_name: Luce
    :varietal:
    :released_on:
    :is_discontinued: false
    :has_limited_time_offer: false
    :has_clearance_sale: false
    :has_bonus_reward_miles: false
    :has_value_added_promotion: false
    :is_seasonal: false
    :is_vqa: false
    :is_kosher: false
    :description:
    :serving_suggestion:
    :tasting_note:
    :value_added_promotion_description:
    :image_thumb_url:
    :image_url:
